[package]
name = "test_vanity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algonaut = "0.4.2"
algonaut_transaction = "0.3.0"